### PR TITLE
fix: set correct Accept header for CONSTRUCT queries

### LINKED ISSUE #47: EasyRdf incorrectly uses 'Accept:' headers
transferred original issue [#301](https://github.com/easyrdf/easyrdf/issues/301)

### PR DESCRIPTION
**Pull request by simontaurus**
fixes #47

### CODE REVIEW

**Comment by k00ni** [comment]
@simontaurus Thank you for the PR! I tried to reproduce the result as described in https://github.com/easyrdf/easyrdf/issues/301#issue-360348064, but was not able to. EasyRdf generates a `Graph` instance, as expected. Please see this [test](https://github.com/sweetrdf/easyrdf/pull/48/files#diff-63043d5e985a83673e9aef5f135ac78dcc4e10911799ba3dbb25bc64e3f05045R613-R624), which works both with and without your adaptions.

Its good to solve old bugs, but this one seems to be fixed in the meantime. What am I missing here?

**Comment by TallTed** [comment]
Looking at the new `Accept:` header, I see a few weird things. It's easier for humans to decipher with one media type per line, and with some whitespace to align things --
```
application/x-httpd-php-source         ,
application/json                       ,
application/ld+json                    ,
application/n-triples                  ,
       text/json               ; q=0.9 ,
application/rdf+json           ; q=0.9 ,
       text/plain              ; q=0.9 ,
       text/ntriples           ; q=0.9 ,
application/ntriples           ; q=0.9 ,
application/x-ntriples         ; q=0.9 ,
       text/turtle             ; q=0.8 ,
application/rdf+xml            ; q=0.8 ,
application/turtle             ; q=0.7 ,
application/x-turtle           ; q=0.7 ,
       text/xml                ; q=0.5 ,
application/xml                ; q=0.5 ,
       text/html               ; q=0.4 ,
application/xhtml+xml          ; q=0.4
```

The first several lines imply `q=1.0`.

Now, several of these are deprecated (e.g., `application/x-ntriples;q=0.9`), and I would suggest that while they may be acceptable, they should have a lower `q` than the type(s) that replaced them.

Further, several of the higher `q` are not associated with RDF, and do not have standard conversion methods (e.g., `text/plain;q=0.9`, `application/x-httpd-php-source`). I suggest that these should have a lower `q` value than *all* RDF-ish types.

If I were building this list, I'd order the types in my actual order of preference, and then set the `q` values to step down the same way. Note that `q` values between `0` and `1` may have 3 digits after the decimal (i.e., `q=0.001` to `q=0.999` ), so there are plenty of values to use to stack this list in order of actual preference.

Giving the `Accept:` header (for all SPARQL queries, not just `CONSTRUCT`) proper consideration should radically improve user experience, especially where users target multiple SPARQL engines over time..

**Comment by simontaurus** [comment]
@k00ni, @TallTed: Many thanks for evaluating this further.
To summarize, easyrdf sends an ill-formed `Accept:` header. Technically any server returning e.g.
`application/x-httpd-php-source`, `application/json` (q=1.0) or `text/html` (q=0.4) would behave correct but this may lead to parsing errors on the client side.
While dbpedias endpoint implementations 'cures' this, specifically blazegraph e.g. at https://query.wikidata.org/sparql returns `application/sparql-results+json` confronted with the easyrdf default header (which is maybe ill-formed too, because `application/sparql-results+json` was never accepted but may regarded as subtype of `application/json` which was accepted). In this case the following line will create a `Result` instead of a `Graph`:
https://github.com/sweetrdf/easyrdf/blob/c7b0a9dbcb211eb7de03ee99ff5b52d17f2a8e64/lib/Sparql/Client.php#L391-L392

The fix will remove `application/json` and non-RDF types from `Accept:` fixing the behavior observed for blazegraph.

**Comment by simontaurus** [comment]
I've added a second test with wikidata as endpoint which fails with the current main branch, see https://github.com/RepoLab/easyrdf/actions/runs/9030250747/job/24814145081

**Comment by k00ni** [comment]
First, thanks to both of you for taking the time to make this fork better.

@TallTed I agree with your statements. EasyRdf should use proper communication so users can get what they expect. With these changes we can take a first step in this direction.

@simontaurus thanks for the feedback, I refined your adaptions and added a few more.

I dug around and have to say EasyRdf is a freaking mess in this regard. For instance, why is SVG part of the format list ([reference](https://github.com/sweetrdf/easyrdf/blob/master/lib/Format.php#L701-L709))? :laughing:

There is another instance where the "broken" `getHttpAcceptHeader` is used: in `Graph::load` > https://github.com/sweetrdf/easyrdf/blob/master/lib/Graph.php#L328-L330. I adapted it using the same code as in `Client::executeQuery` ([ref](https://github.com/sweetrdf/easyrdf/pull/48/files#diff-03db4c2a611aa1f459c1dba753c0282237a616d9c0c4e1dfaf73b273f5fe415a)).

This test demonstrates that the change in `Graph::load` works with "strict" services such as WikiData now: https://github.com/sweetrdf/easyrdf/pull/48/files#diff-4e89689682eaed7ea1f99496cf46701cf4f4f5d92f4c0e74ad35ea6ec5b48a44R400. Without this change it throws the following exception: `No parser class available for format: sparql-json`

I hope I didn't miss something important here. 

CC @zozlak: you also have a deep knowledge in these areas, is there anything you wanna add here?

File: tests/EasyRdf/Sparql/ClientTest.php [hunk 1]
```diff
@@ -613,13 +613,22 @@ private static function parseAcceptHeader($accept_str)
     public function testIssue47CorrectHeaderForConstructQueries(): void
     {
         Http::setDefaultHttpClient(new HttpClient());
+        $query = 'construct { ?s ?q ?r } where { ?s ?p ?o . ?o ?q ?r } limit 1';
 
+        /*
+         * use DBpedia's SPARQL endpoint and check result
```
Comment (TallTed) [inline tests/EasyRdf/Sparql/ClientTest.php:619]:
```suggestion
         * use DBpedia's SPARQL endpoint to check result
```

File: tests/EasyRdf/Sparql/ClientTest.php [hunk 2]
```diff
@@ -613,13 +613,22 @@ private static function parseAcceptHeader($accept_str)
...
-        $result = $endPoint->query($dummyConstructQueryString);
+        $result = $endPoint->query($query);
+        $this->assertTrue($result instanceof Graph, '$result is an instance of '.get_class($result));
 
-        // its also an instance of Graph without the changes in this PR
-        $this->assertTrue($result instanceof Graph);
+        /*
+         * use DBpedia's SPARQL endpoint and check result
+         */
+        $endpointUrl = 'https://query.wikidata.org/sparql';
```
Comment (TallTed) [inline tests/EasyRdf/Sparql/ClientTest.php:629]:
```suggestion
         * use Wikidata's SPARQL endpoint to check result
         */
        $endpointUrl = 'https://query.wikidata.org/sparql';
```

File: tests/EasyRdf/GraphTest.php [hunk 3]
```diff
@@ -392,6 +393,20 @@ public function testLoadRedirect()
         );
     }
 
+    /**
+     * Setup a Graph instance using a real Client to load a CONSTRUCT result.
```
Comment (TallTed) [inline tests/EasyRdf/GraphTest.php:397]:
```suggestion
     * Set up a Graph instance using a real Client to load a CONSTRUCT result.
```

**Review by TallTed — CHANGES_REQUESTED** [review]

**Comment by simontaurus** [comment]
@k00ni: From my side we are good to go 👍
